version: "3.8"
services:
  db:
    image: mysql:8.0.33
    container_name: festago-local-db
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: festago
      MYSQL_USER: festago
      MYSQL_PASSWORD: festago
      TZ: Asia/Seoul
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci" ]
