spring:
  profiles:
    active: local
  config:
    import:
      - classpath:/festago-config/backend/application-dev.yml
      - classpath:/festago-config/backend/application-prod.yml
      - classpath:/festago-config/backend/application-infra.yml
