name: Assign Reviewer By Label
on:
  pull_request:
    types:
      - unlabeled
      - labeled

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: all-label
        id: all-label
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          labels: '[ "ALL" ]'
          reviewers: '["BGuga", "seokjin8678", "xxeol2", "carsago", "SeongHoonC", "EmilyCh0", "re4rk"]'
          remove-when-no-label: "true"
      - name: an-label
        id: an-label
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          labels: '[ "AN" ]'
          reviewers: '["SeongHoonC", "EmilyCh0", "re4rk"]'
          remove-when-no-label: "true"
      - name: be-label
        id: be-label
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          labels: '[ "BE" ]'
          reviewers: '["BGuga", "seokjin8678", "xxeol2", "carsago"]'
          remove-when-no-label: "true"
