name: CD-Back-Dev

on:
  push:
    branches:
      - dev
    paths: 'backend/**'

  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: 자바 설치
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: gradlew 권한 부여
        run: chmod +x gradlew

      - name: Gradle Test
        run: ./gradlew test

      - name: trigger to jenkins dev cd
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: "festago"
          token: ${{ secrets.JENKINS_API_TOKEN}}
          job: "festago-dev-cd"
