name: CD-Back-Dev

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: install java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: assign grant gradlew
        run: chmod +x gradlew

      - name: bootJar with gradle
        run: ./gradlew bootJar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ vars.DOCKER_HUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_DEV_LOGIN_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_DEV_TAG }}
          platforms: linux/amd64

      - name: run application use ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.FESTAGO_DEV_IP }}
          username: ${{ vars.FESTAGO_DEV_USERNAME }}
          key: ${{secrets.FESTAGO_DEV_SSH_KEY}}
          script_stop: true
          script: ${{ vars.FESTAGO_DEV_DEPLOY_COMMAND }}
