name: CD-Back-Dev

on:
  push:
    branches:
      - dev
    paths: 'backend/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: install java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: assign grant gradlew
        run: chmod +x gradlew

      - name: bootJar with gradle
        run: ./gradlew bootJar

      # 2023-11-23 기준 EC2 프리티어 사용으로 인해 DEV 환경을 PROD 환경에서 실행함
      - name: deploy use scp
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.FESTAGO_PROD_IP}}
          username: ${{secrets.FESTAGO_PROD_USERNAME}}
          key: ${{secrets.FESTAGO_SSH_KEY}}
          source: "./backend/build/libs/*.jar"
          target: ${{ vars.FESTAGO_PROD_JAR_DIR }}
          strip_components: 3

      - name: run application use ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.FESTAGO_PROD_IP}}
          username: ${{secrets.FESTAGO_PROD_USERNAME}}
          key: ${{secrets.FESTAGO_SSH_KEY}}
          script_stop: true
          script: ${{ vars.FESTAGO_DEV_DEPLOY_COMMAND }}
