name: CD-Back-Prod

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: install java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: assign grant gradlew
        run: chmod +x gradlew

      - name: bootJar with gradle
        run: ./gradlew bootJar

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ vars.DOCKER_HUB_PROD_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PROD_LOGIN_TOKEN }}

      - name: Build And Push docker image
        run: docker build --platform linux/arm64/v8 --push --tag ${{ vars.DOCKER_PROD_TAG }} .

      - name: run application use ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.FESTAGO_PROD_IP }}
          username: ${{ vars.FESTAGO_PROD_USERNAME }}
          key: ${{secrets.FESTAGO_PROD_SSH_KEY}}
          script_stop: true
          script: ${{ vars.FESTAGO_PROD_DEPLOY_COMMAND }}
